#!/bin/sh
###
# Installing PhantomJS
###
# Adding PPA for PhantomJS
apt-get update
apt-get install -y \
  software-properties-common
add-apt-repository ppa:tanguy-patte/phantomjs
apt-get update
apt-get install -y \
#  phantomjs \
  git \
  python \
  nodejs \
  curl \
  wget \
  nano \
  vim
apt-get clean
wget -qO- https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2 |tar xjv -C /usr/local
ln -s ls -l /usr/local/phantomjs-1.9.8-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs
###
# Installing CasperJS
###
# Cloning Repo
git clone git://github.com/casperjs/casperjs.git
cd casperjs
git checkout ${CASPERJS_VERSION}
cd ..
# Removing history
rm -rf casperjs/.git
mv casperjs /opt/
ln -sf /opt/casperjs/bin/casperjs /usr/local/bin/casperjs
cd /opt/casperjs
rm -rf *.gemspec docs rpm samples
apt-get remove -y \
  git
