#!/bin/sh

#fail script if errors
set -e

###
# Installing PhantomJS
apt-get update
apt-get install -y \
  phantomjs \
  git \
  python \
  nodejs \
  curl \
  wget \
  nano \
  vim
apt-get clean
###
# Installing CasperJS
###
# Cloning Repo
git clone git://github.com/casperjs/casperjs.git
cd casperjs
git checkout ${CASPERJS_VERSION}
cd ..
# Removing history
rm -rf casperjs/.git
mv casperjs /opt/
ln -sf /opt/casperjs/bin/casperjs /usr/local/bin/casperjs
cd /opt/casperjs
rm -rf *.gemspec docs rpm samples
apt-get remove -y \
  git

phantomjs --version
casperjs --version
